version: "3"
services:
  api:
    image: grocery-api:latest
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
